### ISSUE TITLE
Entering BASIC auth password doesn't work

### ISSUE THREAD

**Issue by ghost** [nirvdrum/svn2git#174]
Executing
`svn2git -v --username "mylogin@blah.com" http://10.68.8.14/svn/repo/`

leads to git-svn asking for password:

```
Running command: git svn init --prefix=svn/ --username=mylogin@blah.com --no-metadata --trunk=trunk --tags=tags --branches=branches http://10.68.8.14/svn/repo/
Initialized empty Git repository in /home/yura/p/repo/.git/
Authentication realm: <http://10.68.8.14:80> repo-svn
Password for 'mylogin@blah.com':
```

at which stage entering any text does nothing. Enter key does nothing. The only thing I can do is press Ctrl+C:

```
 /var/lib/gems/1.9.1/gems/svn2git-2.3.2/lib/svn2git/migration.rb:421:in `join': Interrupt
        from /var/lib/gems/1.9.1/gems/svn2git-2.3.2/lib/svn2git/migration.rb:421:in `each'
        from /var/lib/gems/1.9.1/gems/svn2git-2.3.2/lib/svn2git/migration.rb:421:in `block in run_command'
        from /var/lib/gems/1.9.1/gems/svn2git-2.3.2/lib/svn2git/migration.rb:388:in `popen'
        from /var/lib/gems/1.9.1/gems/svn2git-2.3.2/lib/svn2git/migration.rb:388:in `run_command'
        from /var/lib/gems/1.9.1/gems/svn2git-2.3.2/lib/svn2git/migration.rb:202:in `clone!'
        from /var/lib/gems/1.9.1/gems/svn2git-2.3.2/lib/svn2git/migration.rb:34:in `run!'
        from /var/lib/gems/1.9.1/gems/svn2git-2.3.2/bin/svn2git:27:in `<top (required)>'
        from /usr/local/bin/svn2git:23:in `load'
        from /usr/local/bin/svn2git:23:in `<main>'
```

When I execute the `git svn` command stand-alone, its password prompts works all right.

Giving the password as stdin to the svn2git process doesn't work either, but in another way: git-svn just asks for a password three times in a row and then quits with the auth failed message.

svn2git 2.3.2, ruby 1.9.3, Debian.

**Comment by asfdfdfd** [comment]
This bug is still here. 

aliceinwire's workaround works.

**Comment by vietvudanh** [comment]
Confirm the bug still around, MacOS 10.12.5
