### ISSUE TITLE
using --username and --passord not working as expected

### ISSUE THREAD

**Issue by casmer** [nirvdrum/svn2git#195]
Two things I found on Ubuntu 14.04 LTS.
1. If you use just --username when the prompt comes up you have to hit Enter then your password, then enter again. The first enter at the prompt should not be required.
2. if you provide the --password option it says it does not work.

**Comment by RomanVolak** [comment]
I have the same problems. Test with http://argopdf.tigris.org/svn/argopdf/trunk and username guest and password '' (empty):
svn2git http://argopdf.tigris.org/svn/argopdf/trunk --rootistrunk --username guest --password '' 
not known option password. Without option password : Password for 'guest': (ENTER) no reaction.
I have build gitversion from source with gem build svn2git.gemspec && gem install svn2git-version.gem on Lubuntu 15.04

Thanks a lot 
Roman

**Comment by garyStofer** [comment]
I can confirm the findings of casmer on Kubuntu   15.04 as well.

There is no --password option in the migrate.rb file 
If you do as casmer says by pressing enter first then the password then enter again it works -- How the heck did you figure that out ?

**Comment by bhushan154** [comment]
Same issue. Is there a fix?

**Comment by garyStofer** [comment]
The trick with the first hitting a blank return , then the password followed by a return again seems to work .

**Comment by Gl4di4torRr** [comment]
same issue. Is there a fix in progress?

/usr/lib/ruby/1.8/optparse.rb:1450:in `complete': invalid option: --password (OptionParser::InvalidOption)
	from /usr/lib/ruby/1.8/optparse.rb:1448:in `catch'
	from /usr/lib/ruby/1.8/optparse.rb:1448:in `complete'
	from /usr/lib/ruby/1.8/optparse.rb:1261:in `parse_in_order'
	from /usr/lib/ruby/1.8/optparse.rb:1254:in `catch'
	from /usr/lib/ruby/1.8/optparse.rb:1254:in `parse_in_order'
	from /usr/lib/ruby/1.8/optparse.rb:1248:in `order!'
	from /usr/lib/ruby/1.8/optparse.rb:1339:in `permute!'
	from /usr/lib/ruby/1.8/optparse.rb:1360:in `parse!'
	from /usr/lib/ruby/gems/1.8/gems/svn2git-2.3.2/lib/svn2git/migration.rb:146:in `parse'
	from /usr/lib/ruby/gems/1.8/gems/svn2git-2.3.2/lib/svn2git/migration.rb:14:in `initialize'
	from /usr/lib/ruby/gems/1.8/gems/svn2git-2.3.2/bin/svn2git:26:in `new'
	from /usr/lib/ruby/gems/1.8/gems/svn2git-2.3.2/bin/svn2git:26
	from /usr/bin/svn2git:19:in `load'
	from /usr/bin/svn2git:19

**Comment by Gl4di4torRr** [comment]
A workaround for this right now:
yes PASS | svn2git SVN_URL --username USER

**Comment by Zitrax** [comment]
I had the same issue with the blank when entering the password.

In addition I got `unknown option: password` when it ran the subcommand `git svn init` if I passed `--password` to svn2git.

**Comment by Gl4di4torRr** [comment]
@Zitrax have you tried my solution above?

**Comment by Zitrax** [comment]
@Gl4di4torRr After I checked out an svn repo elsewhere the svn2git script stop complaining so I didn't persue it further.

**Comment by Gl4di4torRr** [comment]
:+1:

**Comment by jacobwwang** [comment]
@Gl4di4torRr 
thanks
re: "yes PASS | svn2git SVN_URL --username USER"
it works for me

**Comment by smehdux** [comment]
> 
> 
> A workaround for this right now:
> yes PASS | svn2git SVN_URL --username USER

Thanks, you saved my day :)

**Comment by ibaoger** [comment]
```
gem uninstall svn2git
gem install svn2git3
SVN2GIT_PASSWORD=<<password>> svn2git http://svn.example.com/path/to/repo --username <<user_with_perms>>
```

this issue has resolved by @jesteves, I pushed it to rubygems.
