### ISSUE TITLE
Use global $stdin instead of local variable

### ISSUE THREAD

**Issue by sagiru** [nirvdrum/svn2git#284]
The stdin bypass will use a local variable stdin instead of $stdin and
    it will result in the following error:
    
''''
Traceback (most recent call last):
            2: from /usr/lib/ruby/vendor_ruby/svn2git/migration.rb:432:in `block (2 levels) in run_command'
            1: from /usr/lib/ruby/vendor_ruby/svn2git/migration.rb:432:in `loop'
    /usr/lib/ruby/vendor_ruby/svn2git/migration.rb:438:in `block (3 levels) in run_command': undefined local variable or method `stdin' for #<Svn2Git::Migration:0x0000555b7c945cc8> (NameError)
    Did you mean?  String
''''
If will file a merge request to fix it.

[1] https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=905832

**Comment by lhuria94** [comment]
Did you find a solution for this?

**Comment by VenkeyK** [comment]
Hi,
Does anyone find a solution for the above error?

**Comment by sagiru** [comment]
> Hi,
> Does anyone find a solution for the above error?

Hi,

i filed a pullrequest (285), maybe it's helpful.

Regards 
Sascha
