### ISSUE TITLE
how to trouble shoot svb2git

### ISSUE THREAD

**Issue by cjohnshu** [nirvdrum/svn2git#321]
I use ruby svn2git.
I have the following error

F:\PRJ\dba>svn2git svn://localhost/ --prefix=svn/ --trunk / --nobranches --notags --authors dba_authors.txt
D:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/svn2git-2.4.0/lib/svn2git/migration.rb:58:in `parse': undefined method `exists?' for File:Class (NoMethodError)

      if File.exists?(File.expand_path(DEFAULT_AUTHORS_FILE))
             ^^^^^^^^
Did you mean?  exist?
        from D:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/svn2git-2.4.0/lib/svn2git/migration.rb:14:in `initialize'
        from D:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/svn2git-2.4.0/bin/svn2git:26:in `new'
        from D:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/svn2git-2.4.0/bin/svn2git:26:in `<top (required)>'
        from D:/Ruby32-x64/bin/svn2git:32:in `load'
        from D:/Ruby32-x64/bin/svn2git:32:in `<main>'

**Comment by cjohnshu** [comment]
This version of svn2git should ignore method `exists?' but the migration.rb in this build still reference to it.
Line 58 of migration.rb
#if File.exists?(File.expand_path(DEFAULT_AUTHORS_FILE))
# options[:authors] = DEFAULT_AUTHORS_FILE
#end

**Comment by ghost** [comment]
Same issue here, installed via gem. Looks like ruby removed the plural method exists in version 3.2.0, should use the singular File.exist? instead.

**Comment by josh6025** [comment]
> Same issue here, installed via gem. Looks like ruby removed the plural method exists in version 3.2.0, should use the singular File.exist? instead.

Thanks for that, I ended up downloading **Ruby 3.1.4-1** and was able to continue without any issues.

**Comment by Rikj000** [comment]
## Work Around for `v2.4.0`
Open `migration.db` as admin in your favorite text editor, preferably with line numbering,   
I'm on Manjaro Linux, so for me the path was different,   
your error should tell you which file though.

For me on Linux it was under:   
`/usr/lib/ruby/gems/3.2.0/gems/svn2git-2.4.0/lib/svn2git/migration.rb`
For @cjohnshu on Windows I can see it's under:   
`D:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/svn2git-2.4.0/lib/svn2git/migration.rb`

Then alter line 58 as following:
```diff
- if File.exists?(File.expand_path(DEFAULT_AUTHORS_FILE))
+ if File.exist?(File.expand_path(DEFAULT_AUTHORS_FILE))
```

Save and exit, `svn2git` should work as expected now, no Ruby downgrade required! :tada: 

## Permanent solution
See MR by @sudipm-mukherjee: https://github.com/nirvdrum/svn2git/pull/333

**Comment by IvaskevychYuriy** [comment]
> /usr/lib/ruby/gems/3.2.0/gems/svn2git-2.4.0/lib

For me on Ubuntu 24.04 & Ruby 3.2.3 this was instead located under
`/var/lib/gems/3.2.0/gems/svn2git-2.4.0/lib...`
