### ISSUE TITLE
Could not work on wsl2.

### ISSUE THREAD

**Issue by lc4** [nirvdrum/svn2git#331]
Here is my system info:
WSL version: 2.1.5.0
Kernel version: 5.15.146.1-2
WSLg version: 1.0.60
MSRDC version: 1.2.5105
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.19044.3086

I tried it on an independent Virtualbox ubuntu system, and it works, then I want to increase the converting speed, and tried to run it on wsl2, the installation process is ok, but when running svn2git, it give out error message.

**Comment by himpson** [comment]
@lc4 What error are you seeing? I can run this under WSL2 without issue

**Comment by jb68** [comment]
New WSL2 
```
svn2git --help
/var/lib/gems/3.2.0/gems/svn2git-2.4.0/lib/svn2git/migration.rb:58:in `parse': undefined method `exists?' for File:Class (NoMethodError)

      if File.exists?(File.expand_path(DEFAULT_AUTHORS_FILE))
             ^^^^^^^^
Did you mean?  exist?
        from /var/lib/gems/3.2.0/gems/svn2git-2.4.0/lib/svn2git/migration.rb:14:in `initialize'
        from /var/lib/gems/3.2.0/gems/svn2git-2.4.0/bin/svn2git:26:in `new'
        from /var/lib/gems/3.2.0/gems/svn2git-2.4.0/bin/svn2git:26:in `<top (required)>'
        from /usr/local/bin/svn2git:25:in `load'
        from /usr/local/bin/svn2git:25:in `<main>'
```

**Comment by jhoos70** [comment]
Same for me. 

`/var/lib/gems/3.2.0/gems/svn2git-2.4.0/lib/svn2git/migration.rb:58:in `parse': undefined method `exists?' for File:Class (NoMethodError)

      if File.exists?(File.expand_path(DEFAULT_AUTHORS_FILE))
             ^^^^^^^^
Did you mean?  exist?
        from /var/lib/gems/3.2.0/gems/svn2git-2.4.0/lib/svn2git/migration.rb:14:in `initialize'
        from /var/lib/gems/3.2.0/gems/svn2git-2.4.0/bin/svn2git:26:in `new'
        from /var/lib/gems/3.2.0/gems/svn2git-2.4.0/bin/svn2git:26:in `<top (required)>'
        from /usr/local/bin/svn2git:25:in `load'
        from /usr/local/bin/svn2git:25:in `<main>'`

**Comment by MiKom** [comment]
@jhoos70 there's a workaround: https://github.com/nirvdrum/svn2git/issues/321#issuecomment-2489592639
