### ISSUE TITLE
Problem connection to password protected SVN repo

### ISSUE THREAD

**Issue by markstickley** [nirvdrum/svn2git#59]
Hi,

I'm trying to convert an SVN repo to git. The SVN repo sits on my home server which I have aliased in my `hosts` file to `svnserver`. When I run this command:

```
svn://svnserver/qkschool.org.uk -v --username markstickley
```

it just sits there showing only the following output:

```
Running command: git svn init --prefix=svn/ --username=markstickley --no-metadata --trunk=trunk --tags=tags --branches=branches svn://svnserver/qkschool.org.uk
Initialized empty Git repository in /Users/markstickley/workspace/qkschool.org.uk/.git/
Authentication realm: <svn://svnserver:3690> 2d1a41b5-b418-457c-9cb5-d753d313de4d
```

I left it along for hours in case it was doing something. Nada. When I press ctrl+c I get this, if it's any help:

```
/Users/markstickley/.rvm/gems/ruby-1.9.2-p320/gems/svn2git-2.2.1/lib/svn2git/migration.rb:295:in `each': Interrupt
    from /Users/markstickley/.rvm/gems/ruby-1.9.2-p320/gems/svn2git-2.2.1/lib/svn2git/migration.rb:295:in `block in run_command'
    from /Users/markstickley/.rvm/gems/ruby-1.9.2-p320/gems/svn2git-2.2.1/lib/svn2git/migration.rb:294:in `popen'
    from /Users/markstickley/.rvm/gems/ruby-1.9.2-p320/gems/svn2git-2.2.1/lib/svn2git/migration.rb:294:in `run_command'
    from /Users/markstickley/.rvm/gems/ruby-1.9.2-p320/gems/svn2git-2.2.1/lib/svn2git/migration.rb:178:in `clone!'
    from /Users/markstickley/.rvm/gems/ruby-1.9.2-p320/gems/svn2git-2.2.1/lib/svn2git/migration.rb:27:in `run!'
    from /Users/markstickley/.rvm/gems/ruby-1.9.2-p320/gems/svn2git-2.2.1/bin/svn2git:26:in `<top (required)>'
    from /Users/markstickley/.rvm/gems/ruby-1.9.2-p320/bin/svn2git:23:in `load'
    from /Users/markstickley/.rvm/gems/ruby-1.9.2-p320/bin/svn2git:23:in `<main>'
```

Thanks!

**Comment by JesseKPhillips** [comment]
When it asked for my password 4 times, I answered it 4 times. It finally worked. Maybe the way it is interacting with SVN it is asked for the password multiple times, maybe how many times it asks depends on the security of your SVN server.

**Comment by MilkyWayJoe** [comment]
I'm having this issue at the moment. It only asks the password once. When I hit return nothing happens. It just sits there until i command c

**Comment by timmmt** [comment]
The way it worked for me was either first pressing Enter, then username, then enter, enter, then password. Or something like that. Finally I've given up and made sure my SVN password is saved/remembered BEFORE running svn2git. Easiest done by random svn checkout from nearby svn path. Not a fix, but a workaround.

**Comment by andersondsouzaatcrimsoni** [comment]
I have same issue as MilkyWayJoe. It asks for password and nothing happens even after entering it and pressing enter. it just sits there.

**Comment by VirtuoUK** [comment]
Same issue, prompts for password but does nothing after pressing enter, none of the above workarounds do anything for me.

**Comment by Ishan1987** [comment]
@markstickley I faced the same issue while running "svn2git svn-url --metadata". It was asking to enter certification type but was not proceeding further post adding input P or t. So to resolve this issue, i had checked out svn repo manually using **svn co svn-url** that gave me a prompt to enter cert type ( P, T or R). I added p and it started checking out svn repo code in my local working directory. Then i ran _svn2git svn-url --metadata_ in separate directory and found prior steps resolved my cert issue. Good luck.

**Comment by jvitorinoj** [comment]
Workaround:
First run  
`git svn init --prefix=svn/ --username='user' --no-metadata --no-minimize-url --trunk='trunk' --tags='tags' --branches='branches' http://svnserver/projectA`
This will ask for login and password.
Then run svn2git (no need for password this time)

**Comment by desbest** [comment]
There is a fork of svn2git called svn2gitnet that solves this issue that is a complete rewrite. It works on windows, mac and linux.
[Find out about svn2gitnet here](https://github.com/mazong1123/svn2gitnet)
